#include "script/papyrus/transpile.h"

#include <set>
#include <string>
#include <unordered_map>
#include <vector>

#include "script/papyrus/opcode.h"
#include "script/papyrus/transpile_internal.h"

namespace rx::script::papyrus {
namespace {

using namespace detail;

// Emits the class and file structure around each function body, which
// decompiler.cc reconstructs. It resolves the per-object naming the body relies
// on: auto-property backing fields, function/field name clashes, and the
// canonical casing of every member and function.
class Emitter {
 public:
  Emitter(const PexFile& pex, const TranspileOptions& opts) : pex_(pex), opts_(opts) {}

  std::string Run() {
    Line("// <auto-generated> EXPERIMENTAL Papyrus->C# decompilation.");
    Line("// Source: " + (pex_.source_file_name.empty() ? "<unknown>" : pex_.source_file_name));
    Line("// Reconstructed by tools/papyrus pex2cs. Review before trusting.");
    Line("using System;");
    if (Harness())
      Line("using static Recreation.Decompiled.__Engine;");
    else
      Line("using Recreation;");
    Line("");
    Line("namespace " + opts_.namespace_name + ";");
    Line("");
    for (const Object& obj : pex_.objects) EmitObject(obj);
    return out_;
  }

 private:
  const std::string& Str(StringIndex i) const { return pex_.Str(i); }

  bool Harness() const { return opts_.compile_harness || opts_.runner; }
  bool Runner() const { return opts_.runner; }
  // In runner mode an object member is seeded with a recorder so calls on it log
  // instead of dereferencing null. Elsewhere it keeps its declared default.
  std::string MemberSeed(const std::string& name) {
    return Runner() ? " = new Eng(\"" + name + "\")" : " = default";
  }

  std::string DeclType(const std::string& papyrus) { return DeclTypeFor(papyrus, Harness()); }

  DecompileCtx Ctx() const {
    return {pex_, &backing_, &fn_rename_, &case_names_, &case_fns_, &opts_};
  }

  // Names the body references with a "::" prefix that are neither a per-function
  // compiler temp nor a declared member. These are the engine's implicit members,
  // chiefly "::State". Returned as raw Papyrus names, deduplicated.
  std::set<std::string> ImplicitMembers(const Object& obj) {
    std::set<std::string> declared;
    for (const MemberVariable& v : obj.variables) declared.insert(Str(v.name));
    std::set<std::string> implicit;
    for (const State& s : obj.states) {
      for (const NamedFunction& nf : s.functions) {
        std::set<std::string> locals;
        for (const TypedName& l : nf.function.locals) locals.insert(Str(l.name));
        auto scan = [&](const std::vector<VariableData>& ops) {
          for (const VariableData& v : ops) {
            if (v.type != VariableData::Type::kIdentifier) continue;
            const std::string& n = Str(v.string_index);
            if (n.size() < 2 || n[0] != ':' || n[1] != ':') continue;
            if (locals.count(n) || declared.count(n)) continue;
            implicit.insert(n);
          }
        };
        for (const Instruction& in : nf.function.code) {
          scan(in.args);
          scan(in.var_args);
        }
      }
    }
    return implicit;
  }

  // Identifiers the body reads that resolve to no local, param, declared member,
  // property, or implicit member, meaning names inherited from a parent script.
  // Returns the canonical C# field names to declare, and folds every casing
  // variant onto the one field via case_names_. Harness only.
  std::set<std::string> HarnessUnresolved(const Object& obj) {
    std::set<std::string> object_lower;
    for (const auto& [lower, _] : case_names_) object_lower.insert(lower);
    for (const std::string& raw : ImplicitMembers(obj)) object_lower.insert(ToLower(raw));
    std::set<std::string> fields;
    auto scan = [&](const Function& fn) {
      std::set<std::string> scoped = object_lower;
      for (const TypedName& p : fn.params) scoped.insert(ToLower(Str(p.name)));
      for (const TypedName& l : fn.locals) scoped.insert(ToLower(Str(l.name)));
      auto consider_name = [&](const std::string& n) {
        if (n.empty() || (n.size() >= 2 && n[0] == ':' && n[1] == ':')) return;
        if (IEquals(n, "self") || IEquals(n, "value")) return;  // value is the setter param
        std::string lower = ToLower(n);
        if (scoped.count(lower)) return;
        std::string canon = Sanitize(n);
        case_names_.emplace(lower, canon);
        fields.insert(canon);
      };
      // The compiler often loads `self` into a temp (sometimes via a cast to the
      // script type) and reaches a property through that temp, so track the temps
      // that currently hold self to recognise those self-property accesses.
      std::set<std::string> self_temps;
      auto is_self = [&](const VariableData& v) {
        if (v.type != VariableData::Type::kIdentifier) return false;
        const std::string& n = Str(v.string_index);
        return IEquals(n, "self") || self_temps.count(n) != 0;
      };
      for (const Instruction& in : fn.code) {
        const Roles r = RolesOf(in.op);
        auto op = [&](int idx) {
          if (idx < 0 || idx >= static_cast<int>(in.args.size())) return;
          if (in.args[idx].type == VariableData::Type::kIdentifier)
            consider_name(Str(in.args[idx].string_index));
        };
        for (int idx : r.reads) op(idx);
        if (r.dest >= 0) op(r.dest);
        // An inherited property reached on self carries its name in args[0],
        // outside the read set, so pick it up here.
        if ((in.op == Op::kPropGet || in.op == Op::kPropSet) && in.args.size() >= 2 &&
            is_self(in.args[1]))
          consider_name(Str(in.args[0].string_index));
        if ((in.op == Op::kAssign || in.op == Op::kCast) && in.args.size() >= 2 &&
            in.args[0].type == VariableData::Type::kIdentifier) {
          if (is_self(in.args[1]))
            self_temps.insert(Str(in.args[0].string_index));
          else
            self_temps.erase(Str(in.args[0].string_index));
        }
      }
    };
    for (const State& s : obj.states)
      for (const NamedFunction& nf : s.functions) scan(nf.function);
    for (const Property& p : obj.properties) {
      if (p.has_getter) scan(p.getter);
      if (p.has_setter) scan(p.setter);
    }
    return fields;
  }

  void EmitObject(const Object& obj) {
    // An auto property owns a hidden backing variable; map it to the property name
    // so the body reads through the property and the field is suppressed below.
    backing_.clear();
    for (const Property& p : obj.properties) {
      if (p.is_auto() && p.auto_var_name != kInvalidString)
        backing_[Str(p.auto_var_name)] = Sanitize(Str(p.name));
    }

    // Papyrus keeps function names in a separate namespace from fields and
    // properties, so a script may have both a `summonPhase` variable and a
    // `summonPhase()` function. C# cannot, so a function whose C# name collides
    // with a data member is renamed (and self-calls follow it).
    std::set<std::string> members;
    for (const MemberVariable& v : obj.variables) {
      if (backing_.count(Str(v.name))) continue;
      members.insert(Sanitize(Str(v.name)));
    }
    for (const Property& p : obj.properties) members.insert(Sanitize(Str(p.name)));
    fn_rename_.clear();
    case_names_.clear();
    case_fns_.clear();
    for (const MemberVariable& v : obj.variables) {
      if (backing_.count(Str(v.name))) continue;
      case_names_[ToLower(Str(v.name))] = Sanitize(Str(v.name));
    }
    for (const Property& p : obj.properties)
      case_names_[ToLower(Str(p.name))] = Sanitize(Str(p.name));
    for (const State& s : obj.states) {
      if (s.name != kInvalidString && !Str(s.name).empty()) continue;  // default state only
      for (const NamedFunction& nf : s.functions) {
        std::string n = Sanitize(Str(nf.name));
        if (members.count(n)) fn_rename_[Str(nf.name)] = n + "_fn";
        case_fns_[ToLower(Str(nf.name))] = members.count(n) ? n + "_fn" : n;
      }
    }

    std::string name = Sanitize(Str(obj.name));
    if (opts_.sink) opts_.sink->declared_types.insert(name);
    std::string parent = Str(obj.parent_class);
    // The harness has no engine base types and routes inherited calls through
    // dynamic, so it drops the `: Parent` clause. The runner instead derives from
    // the recording base so self and inherited calls are logged.
    std::string base = Runner() ? " : Eng"
                       : (Harness() || parent.empty() || IEquals(parent, "none"))
                           ? ""
                           : " : " + Sanitize(parent);
    if (!Str(obj.doc_string).empty()) LineComment(Str(obj.doc_string));
    Line("public class " + name + base);
    Line("{");
    ++indent_;
    if (Runner()) Line("public " + name + "() : base(\"" + name + "\") {}");

    size_t emitted_vars = 0;
    for (const MemberVariable& v : obj.variables) {
      if (backing_.count(Str(v.name))) continue;  // hidden auto-property backing
      EmitMember(v);
      ++emitted_vars;
    }
    // Declare the implicit members the variable table never lists, chiefly
    // "::State", the current state name.
    for (const std::string& raw : ImplicitMembers(obj)) {
      std::string type = IEquals(raw, "::State") ? "string" : "var";
      Line("private " + DeclType(type) + " " + Sanitize(raw) + MemberSeed(Sanitize(raw)) + ";");
      ++emitted_vars;
    }
    // The harness has no base class, so inherited members and constants (such as
    // ObjectReference's Motion_Keyframed) resolve nowhere. Declare each as a
    // dynamic field. The real output keeps `: Parent`, where they resolve.
    if (Harness())
      for (const std::string& field : HarnessUnresolved(obj)) {
        Line("private dynamic " + field + MemberSeed(field) + ";");
        ++emitted_vars;
      }
    if (emitted_vars) Line("");
    for (const Property& p : obj.properties) EmitProperty(obj, p);

    // Functions live inside states. The default state's functions are the
    // script's methods; a named state's are emitted under a state-qualified name.
    for (const State& s : obj.states) {
      std::string sname = Str(s.name);
      if (!sname.empty()) Line("// state " + sname);
      for (const NamedFunction& nf : s.functions) EmitFunction(obj, nf, sname);
    }

    --indent_;
    Line("}");
    Line("");
  }

  void EmitMember(const MemberVariable& v) {
    std::string type = DeclType(Str(v.type));
    std::string name = Sanitize(Str(v.name));
    std::string line = "private " + type + " " + name;
    if (Runner()) {
      Line(line + MemberSeed(name) + ";");
      return;
    }
    const VariableData& iv = v.initial_value;
    switch (iv.type) {
      case VariableData::Type::kInteger: line += " = " + std::to_string(iv.int_value); break;
      case VariableData::Type::kFloat:   line += " = " + FormatFloat(iv.float_value); break;
      case VariableData::Type::kBool:    line += iv.bool_value ? " = true" : " = false"; break;
      case VariableData::Type::kString:  line += " = " + EscapeString(Str(iv.string_index)); break;
      default: break;
    }
    Line(line + ";");
  }

  void EmitProperty(const Object& obj, const Property& p) {
    std::string type = DeclType(Str(p.type));
    std::string name = Sanitize(Str(p.name));
    if (p.is_auto()) {
      std::string acc = "{ get; set; }";
      if (p.readable() && !p.writable()) acc = "{ get; }";
      Line("public " + type + " " + name + " " + acc + (Runner() ? MemberSeed(name) + ";" : ""));
      Line("");
      return;
    }
    Line("public " + type + " " + name);
    Line("{");
    ++indent_;
    if (p.has_getter) {
      Line("get");
      Line("{");
      ++indent_;
      EmitLocals(p.getter);
      DecompileFunction(Ctx(), p.getter, out_, indent_);
      --indent_;
      Line("}");
    }
    if (p.has_setter) {
      Line("set");
      Line("{");
      ++indent_;
      // The setter's single value parameter is C#'s implicit `value`, aliased so
      // it is not re-declared and its references resolve.
      std::string value_param = p.setter.params.empty() ? "" : Str(p.setter.params[0].name);
      EmitLocals(p.setter, value_param);
      DecompileFunction(Ctx(), p.setter, out_, indent_, value_param);
      --indent_;
      Line("}");
    }
    --indent_;
    Line("}");
    Line("");
  }

  void EmitFunction(const Object& obj, const NamedFunction& nf, const std::string& state) {
    const Function& fn = nf.function;
    std::string name = Sanitize(Str(nf.name));
    std::string ret = DeclType(Str(fn.return_type));

    // A Papyrus script can define the same function in several states. C# has no
    // states, so a state's override is emitted under a state-qualified name. A
    // default-state function that collides with a field is renamed instead.
    if (!state.empty()) {
      name = Sanitize(state) + "_" + name;
    } else {
      auto rit = fn_rename_.find(Str(nf.name));
      if (rit != fn_rename_.end()) name = rit->second;
    }

    if (opts_.emit_disasm_comments) EmitDisasm(fn);
    if (!state.empty()) Line("// state " + state);
    if (!Str(fn.doc_string).empty()) LineComment(Str(fn.doc_string));

    std::string sig = "public ";
    if (fn.is_global) sig += "static ";
    sig += ret + " " + name + "(";
    for (size_t i = 0; i < fn.params.size(); ++i) {
      if (i) sig += ", ";
      sig += DeclType(Str(fn.params[i].type)) + " " + Sanitize(Str(fn.params[i].name));
    }
    sig += ")";
    Line(sig);
    Line("{");
    ++indent_;
    if (fn.is_native) {
      Line("// native: implemented by the engine.");
      if (ret != "void") Line("return default;");
    } else {
      EmitLocals(fn);
      DecompileFunction(Ctx(), fn, out_, indent_);
      // Papyrus lets a non-Void function fall off the end with an implicit zero
      // return, which C# does not, so close that path explicitly.
      if (ret != "void" && EndReachable(fn)) Line("return default;");
    }
    --indent_;
    Line("}");
    Line("");
  }

  // Declares the user locals up front. Compiler temporaries (the "::" names) are
  // skipped, since the body inlines or materialises them. value_param, if set,
  // names a setter value parameter that must not be declared.
  void EmitLocals(const Function& fn, const std::string& value_param = "") {
    std::set<std::string> params;
    for (const TypedName& p : fn.params) params.insert(Str(p.name));
    if (!value_param.empty()) params.insert(value_param);
    for (const TypedName& l : fn.locals) {
      std::string n = Str(l.name);
      if (n.size() >= 2 && n[0] == ':' && n[1] == ':') continue;  // compiler temp
      if (params.count(n)) continue;
      Line(DeclType(Str(l.type)) + " " + Sanitize(n) + " = default;");
    }
  }

  void EmitDisasm(const Function& fn) {
    Line("/* bytecode:");
    for (size_t i = 0; i < fn.code.size(); ++i) {
      const Instruction& in = fn.code[i];
      std::string s = "  " + std::to_string(i) + ": " + GetOpInfo(in.op).mnemonic;
      for (const VariableData& a : in.args) s += " " + Operand(a);
      for (const VariableData& a : in.var_args) s += " " + Operand(a);
      Line(s);
    }
    Line("*/");
  }

  std::string Operand(const VariableData& v) {
    switch (v.type) {
      case VariableData::Type::kNone: return "None";
      case VariableData::Type::kIdentifier: return Str(v.string_index);
      case VariableData::Type::kString: return EscapeString(Str(v.string_index));
      case VariableData::Type::kInteger: return std::to_string(v.int_value);
      case VariableData::Type::kFloat: return FormatFloat(v.float_value);
      case VariableData::Type::kBool: return v.bool_value ? "true" : "false";
    }
    return "?";
  }

  void Line(const std::string& s) {
    out_.append(static_cast<size_t>(indent_) * 4, ' ');
    out_.append(s);
    out_.push_back('\n');
  }

  // Emits text as a `//` comment. Papyrus doc strings often span several lines,
  // so each embedded line gets its own `//` rather than spilling into the source.
  void LineComment(const std::string& text) {
    size_t start = 0;
    while (start <= text.size()) {
      size_t nl = text.find('\n', start);
      size_t end = (nl == std::string::npos) ? text.size() : nl;
      std::string piece = text.substr(start, end - start);
      if (!piece.empty() && piece.back() == '\r') piece.pop_back();
      Line("// " + piece);
      if (nl == std::string::npos) break;
      start = nl + 1;
    }
  }

  const PexFile& pex_;
  const TranspileOptions& opts_;
  std::string out_;
  int indent_ = 0;
  std::unordered_map<std::string, std::string> backing_;
  std::unordered_map<std::string, std::string> fn_rename_;
  std::unordered_map<std::string, std::string> case_names_;
  std::unordered_map<std::string, std::string> case_fns_;
};

}  // namespace

std::string TranspileToCSharp(const PexFile& pex, const TranspileOptions& opts) {
  return Emitter(pex, opts).Run();
}

std::string TranspileFunctionToCSharp(const PexFile& pex, const Function& fn,
                                      const std::string& cs_name) {
  using namespace detail;
  TranspileOptions opts;  // real mode: concrete types, self-contained for a pure fn
  std::string out = "    public static " + DeclTypeFor(pex.Str(fn.return_type), false) + " " +
                    cs_name + "(";
  for (size_t i = 0; i < fn.params.size(); ++i) {
    if (i) out += ", ";
    out += DeclTypeFor(pex.Str(fn.params[i].type), false) + " " + Sanitize(pex.Str(fn.params[i].name));
  }
  out += ") {\n";
  std::set<std::string> params;
  for (const TypedName& p : fn.params) params.insert(pex.Str(p.name));
  for (const TypedName& l : fn.locals) {
    std::string n = pex.Str(l.name);
    if (n.size() >= 2 && n[0] == ':' && n[1] == ':') continue;
    if (params.count(n)) continue;
    out += "        " + DeclTypeFor(pex.Str(l.type), false) + " " + Sanitize(n) + " = default;\n";
  }
  DecompileFunction({pex, nullptr, nullptr, nullptr, nullptr, &opts}, fn, out, 2);
  if (DeclTypeFor(pex.Str(fn.return_type), false) != "void" && EndReachable(fn))
    out += "        return default;\n";
  out += "    }\n";
  return out;
}

}  // namespace rx::script::papyrus
