package com.recreation.launcher

import android.content.Context
import androidx.core.content.edit
import java.io.File

/** The Bethesda games the engine can load. Each keeps its own Data path so
 *  several can be configured at once; the launcher picks which one to run. */
enum class GameId(val key: String, val display: String) {
    SKYRIM_SE("skyrimse", "Skyrim Special Edition"),
    FALLOUT4("fo4", "Fallout 4"),
    FALLOUT76("fo76", "Fallout 76"),
}

/** What to launch: a configured game, or a built-in demo scene that needs no
 *  assets (useful for verifying the renderer on a device without game data). */
sealed interface LaunchTarget {
    data class Game(val id: GameId) : LaunchTarget
    data class Demo(val scene: String) : LaunchTarget
}

val DEMO_SCENES = listOf("materials", "water", "cornell", "lights", "oit", "meshlet")

/** How a configured Data path looks on disk, used to drive the path indicator. */
enum class PathStatus { EMPTY, MISSING, EXISTS, DATA_DIR }

private val DATA_EXTENSIONS = setOf("esm", "esp", "ba2", "bsa")

/** Classifies a Data-folder path: empty, non-existent, an existing directory, or
 *  one that actually holds game archives/plugins (the strongest signal). */
fun dataPathStatus(path: String): PathStatus {
    if (path.isBlank()) return PathStatus.EMPTY
    val dir = File(path)
    if (!dir.isDirectory) return PathStatus.MISSING
    val looksLikeData = dir.listFiles()?.any {
        it.isFile && it.extension.lowercase() in DATA_EXTENSIONS
    } == true
    return if (looksLikeData) PathStatus.DATA_DIR else PathStatus.EXISTS
}

/** Launcher state: persisted to SharedPreferences for the UI, and serialized to
 *  the engine's recreation.cfg (read by runtime/android_main.cc) on launch. */
data class GameConfig(
    val dataDirs: Map<GameId, String> = emptyMap(),
    val target: LaunchTarget = LaunchTarget.Demo("materials"),
    val validation: Boolean = false,
    val raytracing: Boolean = false,
) {
    fun dataDir(id: GameId): String = dataDirs[id].orEmpty()

    fun withDataDir(id: GameId, path: String): GameConfig =
        copy(dataDirs = dataDirs + (id to path))

    /** Demos always launch; a game needs a Data path that exists on disk. */
    val canLaunch: Boolean
        get() = when (val t = target) {
            is LaunchTarget.Demo -> true
            is LaunchTarget.Game -> dataPathStatus(dataDir(t.id)) in
                setOf(PathStatus.EXISTS, PathStatus.DATA_DIR)
        }

    /** Writes the key=value config the native entry point parses. */
    fun writeNativeConfig(context: Context) {
        val sb = StringBuilder()
        sb.appendLine("# generated by the recreation launcher")
        when (val t = target) {
            is LaunchTarget.Game -> sb.appendLine("active=${t.id.key}")
            is LaunchTarget.Demo -> sb.appendLine("demo=${t.scene}")
        }
        for (id in GameId.entries) {
            val dir = dataDir(id)
            if (dir.isNotBlank()) sb.appendLine("data_dir.${id.key}=$dir")
        }
        sb.appendLine("preset=android")
        sb.appendLine("validation=${if (validation) 1 else 0}")
        sb.appendLine("no_rt=${if (raytracing) 0 else 1}")
        File(context.filesDir, "recreation.cfg").writeText(sb.toString())
    }

    fun save(context: Context) {
        prefs(context).edit {
            for (id in GameId.entries) putString("dir_${id.key}", dataDir(id))
            when (val t = target) {
                is LaunchTarget.Game -> putString("target", "game:${t.id.key}")
                is LaunchTarget.Demo -> putString("target", "demo:${t.scene}")
            }
            putBoolean("validation", validation)
            putBoolean("raytracing", raytracing)
        }
    }

    companion object {
        private fun prefs(context: Context) =
            context.getSharedPreferences("recreation_launcher", Context.MODE_PRIVATE)

        fun load(context: Context): GameConfig {
            val p = prefs(context)
            val dirs = GameId.entries.associateWith { p.getString("dir_${it.key}", "").orEmpty() }
            val target = parseTarget(p.getString("target", "demo:materials")!!)
            return GameConfig(
                dataDirs = dirs,
                target = target,
                validation = p.getBoolean("validation", false),
                raytracing = p.getBoolean("raytracing", false),
            )
        }

        private fun parseTarget(s: String): LaunchTarget = when {
            s.startsWith("game:") -> {
                val key = s.removePrefix("game:")
                LaunchTarget.Game(GameId.entries.firstOrNull { it.key == key } ?: GameId.SKYRIM_SE)
            }
            s.startsWith("demo:") -> LaunchTarget.Demo(s.removePrefix("demo:"))
            else -> LaunchTarget.Demo("materials")
        }
    }
}
